{-# LANGUAGE OverloadedStrings #-}
--
-- lobster-selinux.hs --- Lobster-to-SELinux export test.
--
-- Copyright (C) 2014, Galois, Inc.
-- All Rights Reserved.
--
-- Released under the "BSD3" license.  See the file "LICENSE"
-- for details.
--

import Control.Error (runEitherT)
import System.Environment
import System.Exit
import System.IO

import Lobster.Core
import Lobster.SELinux

import qualified Data.Text.IO      as TIO
import qualified Data.Text.Lazy.IO as TLIO

usage :: IO a
usage = do
  hPutStrLn stderr "usage: lobster-selinux FILENAME"
  exitFailure

parseArgs :: IO FilePath
parseArgs = do
  args <- getArgs
  case args of
    a:_ -> return a
    _   -> usage

main :: IO ()
main = do
  file   <- parseArgs
  result <- runEitherT $ readPolicy file
  case result of
    Left err -> do
      TIO.hPutStrLn stderr (errorMessage err)
      exitFailure
    Right m  -> do
      TLIO.putStrLn "# automatically generated by lobster-selinux"
      TLIO.putStrLn $ exportSELinux m

